### ISSUE TITLE
安卓8.0 启动后台服务适配问题

### ISSUE THREAD

**Issue by CaostGrace** [ixuea/android-downloader#10]
java.lang.IllegalStateException:Not allowed to start service Intent { cmp=com.cdwh.chatapp/cn.woblog.android.downloader.DownloadService }: app is in background uid UidRecord{f50bf80 u0a443 CEM idle change:idle|cached procs:1 seq(0,0,0)}

（1）如果针对 Android 8.0 的应用尝试在不允许其创建后台服务的情况下使用 startService() 函数，
     则该函数将引发一个 IllegalStateException。新的 Context.startForegroundService() 函数将启动一个前台服务。
 
（2）即使应用在后台运行，系统也允许其调用 Context.startForegroundService()。不过，
    应用必须在创建服务后的五秒内调用该服务的 startForeground() 函数。

**Comment by ixueadev** [comment]
Thank you very much for your feedback, We upgraded the code and tested it for the time being, because the application is usually in the foreground when creating a task, So there is no recurrence of your problem. You can test with the latest version, If there are still problems, feel free to feedback or submit pr.
