### ISSUE TITLE
Not allowed to start service 

### ISSUE THREAD

**Issue by wangzhenxing-swzx** [ixuea/android-downloader#21]
**Android Downloader version**:
**Android Version**:
**Issue details/Repro steps**:
11
2020-05-10 01:14:19

#702 java.lang.IllegalStateException
Not allowed to start service Intent { cmp=com.az.portal/cn.woblog.android.downloader.DownloadService }: app is in background uid UidRecord{52533c1 u0a69 TPSL idle change:idle|cached procs:1 seq(0,0,0)}
com.az.portal.application.AZApplication.onCreate(Unknown Source:127)
**Use code**:
```
Please paste your code here
```

**Stack trace**:
```
Please paste stack trace here
```

**Screenshot(if any)**:
Please image url here

**Comment by ixueadev** [comment]
Thank you very much for your feedback, We upgraded the code and tested it for the time being, because the application is usually in the foreground when creating a task, So there is no recurrence of your problem. You can test with the latest version, If there are still problems, feel free to feedback or submit pr.
