### ISSUE TITLE
Stuck on Android 11

### ISSUE THREAD

**Issue by MrWildanMD** [ixuea/android-downloader#30]
![IMG-20211205-WA0004](https://user-images.githubusercontent.com/60354284/144734561-a6c45599-c5e6-4d3b-883b-9f812aaaf245.jpg)

Hi i think its a bug or it didnt work well on Android 11?
the progressbar wont updating at all, but when i check on my download folder the file is exists, it works well on Android 10 and below, thanks

**Comment by mojtabasheikhy** [comment]
Problems due to changing accesses in Android 11 You can solve the problem by changing the address of the file to be downloaded
  File file = new File(getActivity().getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS), "Something");
        if (!file.exists()) {
            file.mkdirs();
       }
 downloadInfo = new DownloadInfo.Builder().setUrl(getLinkAddress())
                .setPath(file+getFileName()+fileType)
                .build();

**Comment by MrWildanMD** [comment]
Thanks for reply,, gotta apply it right now
